[settings.defaults]
image = "{{get_env(name="SYNTHIMAGE") | safe }}"
command = "polkadot"
chain-name = "polkadot-local"
timeout = 1000

[nodes.alice]
validator = true
extra-args = ["--alice"]
image = "{{get_env(name="SYNTHIMAGE") | safe }}"
command = "polkadot"

[nodes.bob]
validator = true
extra-args = ["--bob"]
image = "{{get_env(name="SYNTHIMAGE") | safe }}"
command = "polkadot"

[nodes.charlie]
validator = true
extra-args = ["--charlie"]
image = "{{get_env(name="SYNTHIMAGE") | safe }}"
command = "polkadot"

[nodes.david]
validator = true
image = "{{get_env(name="MALUSIMAGE") | safe }}"
command = "/usr/local/bin/malus"
extra-args = ["dispute-valid-block", "--dave"]
