[settings.defaults]
image = "{{get_env(name="SYNTHIMAGE") | safe }}"
command = "polkadot"
chain-name = "polkadot-local"
timeout = 1000

[nodes.alice]
validator = true
image = "{{get_env(name="SYNTHIMAGE") | safe }}"
command = "polkadot"
extra-args = ["--alice"]

[nodes.bob]
validator = true
image = "{{get_env(name="SYNTHIMAGE") | safe }}"
command = "polkadot"
extra-args = ["--bob"]

[nodes.charlie]
validator = true
image = "{{get_env(name="SYNTHIMAGE") | safe }}"
command = "polkadot"
extra-args = ["--charlie"]

[nodes.david]
validator = true
image = "{{get_env(name="MALUSIMAGE") | safe }}"
command-with-args = "/usr/local/bin/malus  dispute-ancestor --chain rococo-local --dave"
