[settings.defaults]
image = "{{get_env(name="SYNTHIMAGE") | safe }}"
command = "polkadot"
chain-name = "polkadot-local"
timeout = 1000

[nodes.alice]
validator = true
extra-args = ["--alice"]
image = "{{get_env(name="SYNTHIMAGE") | safe }}"
command = "polkadot"

[nodes.bob]
validator = true
extra-args = ["back-garbage-candidate", "--bob"]
image = "{{get_env(name="MALUSIMAGE") | safe }}"
command = "/usr/local/bin/malus"

[nodes.charlie]
validator = true
extra-args = ["back-garbage-candidate", "--charlie"]
image = "{{get_env(name="MALUSIMAGE") | safe }}"
command = "/usr/local/bin/malus"

[nodes.david]
validator = true
extra-args = ["back-garbage-candidate", "--dave"]
image = "{{get_env(name="MALUSIMAGE") | safe }}"
command = "/usr/local/bin/malus"

[nodes.eve]
validator = true
extra-args = ["suggest-garbage-candidate","--eve"]
image = "{{get_env(name="MALUSIMAGE") | safe }}"
command = "/usr/local/bin/malus"
