[settings.defaults]
image = "{{get_env(name="SYNTHIMAGE") | safe }}"
command = "polkadot"
chain-name = "polkadot-local"
timeout = 1000

[nodes.alice]
validator = true
image = "{{get_env(name="SYNTHIMAGE") | safe }}"
command = "polkadot"
extra-args = ["--alice"]

[nodes.bob]
validator = true
image = "{{get_env(name="MALUSIMAGE") | safe }}"
command = "/usr/local/bin/malus"
extra-args = ["back-garbage-candidate", "--bob"]

[nodes.charlie]
validator = true
image = "{{get_env(name="MALUSIMAGE") | safe }}"
command = "/usr/local/bin/malus"
extra-args = ["back-garbage-candidate", "--charlie"]

[nodes.david]
validator = true
image = "{{get_env(name="MALUSIMAGE") | safe }}"
command = "/usr/local/bin/malus"
extra-args = ["back-garbage-candidate", "--dave"]

[nodes.eve]
validator = true
image = "{{get_env(name="MALUSIMAGE") | safe }}"
command = "/usr/local/bin/malus"
extra-args = ["suggest-garbage-candidate","--eve"]
